import { GUIDES } from './guides';

// One entry per platform guide, flattened into a single searchable Q&A.
const guideEntries = Object.entries(GUIDES).map(([platform, guide]) => ({
  id: `guide-${platform}`,
  question: `How do I connect ${platform}?`,
  keywords: [platform, 'connect', 'setup', 'credentials', 'configure'],
  answer: guide.intro,
  steps: guide.steps.map((s) => s.title),
  link: `#/guides?platform=${platform}`,
  linkLabel: `Open the full ${platform} guide`,
}));

// App-behavior questions that aren't covered by a platform guide.
const faqEntries = [
  {
    id: 'faq-ready-status',
    question: 'What does "ready" status mean?',
    keywords: ['ready', 'status', 'sheet', 'column', 'post', 'trigger'],
    answer:
      'A row is only picked up for posting when its mapped status column reads exactly "ready" (case-insensitive, no extra words). Anything else - blank, "posted", "draft" - is left alone.',
  },
  {
    id: 'faq-app-vs-user-creds',
    question: "What's the difference between app credentials and a user's connector?",
    keywords: ['clientid', 'clientsecret', 'app', 'credentials', 'shared', 'peruser', 'refreshtoken'],
    answer:
      'For YouTube, the Client ID and Client Secret belong to one Google Cloud OAuth app, configured once and shared by every user. Each user then only needs their own refresh token and channel ID, generated by authorizing as that specific channel.',
    link: '#/connectors',
    linkLabel: 'Go to Connectors',
  },
  {
    id: 'faq-video-column',
    question: 'What can go in the video column?',
    keywords: ['video', 'link', 'drive', 'url', 'local', 'folder', 'file'],
    answer:
      'A direct video URL, a Google Drive share link (it must be shared as "Anyone with the link"), or - if you set a local video folder - just a filename found in that folder.',
    link: '#/sheet',
    linkLabel: 'Go to Sheet setup',
  },
  {
    id: 'faq-platforms-column',
    question: 'How do I control which platforms a video posts to?',
    keywords: ['platforms', 'column', 'youtube', 'facebook', 'instagram', 'tiktok', 'which'],
    answer:
      'The platforms column takes a comma-separated list, e.g. "youtube,facebook". Only platforms in that list, that the user has connected, get posted to.',
    link: '#/sheet',
    linkLabel: 'Go to Sheet setup',
  },
  {
    id: 'faq-run-not-posting',
    question: 'Why did nothing happen when I clicked "Post ready rows now"?',
    keywords: ['nothing', 'posted', 'ran', 'not working', 'stuck', 'failed', 'no rows'],
    answer:
      'Most often it means no row currently has status exactly "ready", or the row lists a platform the user hasn\'t connected yet. Check the per-row result panel after a run - it shows the specific reason for every row.',
    link: '#/dashboard',
    linkLabel: 'Go to Dashboard',
  },
  {
    id: 'faq-sync-cloud',
    question: 'What does "Sync now" actually do?',
    keywords: ['sync', 'cloud', 'firebase', 'backup', 'google sign in'],
    answer:
      'Sign in with Google to push your local users, sheet settings, and connectors to a Firebase backup so you can restore them if this browser\'s storage is ever cleared. It does not affect posting - posting always reads your local data.',
  },
  {
    id: 'faq-multi-user',
    question: 'Can different users post to different platforms?',
    keywords: ['multiple users', 'per user', 'different platforms', 'each user'],
    answer:
      'Yes - each user has their own sheet connection and their own set of connected platforms, picked independently on their Connectors page.',
    link: '#/',
    linkLabel: 'Go to Users',
  },
];

export const KNOWLEDGE_BASE = [...faqEntries, ...guideEntries];
